---
# tasks file for golem-ethereum

- name: add ethereum ppa
  apt_repository:
    repo: "ppa:ethereum/ethereum"
    state: present
  become: yes

- name: install geth
  apt:
    name: geth
    # Golem 0.11.0 is not compatible with Geth 1.8.x
    # state: latest
    update_cache: yes
  become: yes
  notify: geth updated
